# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OnzDqXex9mBHPq5oG0Pie7qRHxbCOAIz
"""

#!/usr/bin/env python
# coding: utf-8

# 모듈 import
import pandas as pd
from bs4 import BeautifulSoup
import requests

startnumber=1
endnumber=1000
Recipe_PRO = {}

RECIPE_ID_list=[]
COOKING_NO_list=[]
COOKING_DC_list=[]
IMG_URL_list = []
TIP_list =[]

while endnumber<=4000:
    #url 입력
    API_KEY = 'c41ba7a35737e92228906457385f7542b47a6f0549b1b90cfeabaf363c070e9e' #자기 키 입력하기
    url = 'http://211.237.50.150:7080/openapi/'+API_KEY+'/xml/Grid_20150827000000000228_1/'+str(startnumber)+'/'+str(endnumber)
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, 'html.parser')
    
    RECIPE_ID = soup.find_all('recipe_id')
    COOKING_NO = soup.find_all('cooking_no')
    COOKING_DC = soup.find_all('cooking_dc')
    IMG_URL = soup.find_all('stre_step_image_url')
    TIP = soup.find_all('step_tip')
    
    for code in RECIPE_ID :
        RECIPE_ID_list.append(code.text)
    for code in COOKING_NO :
        COOKING_NO_list.append(code.text)
    for code in COOKING_DC :
        COOKING_DC_list.append(code.text)
    for code in IMG_URL :
        IMG_URL_list.append(code.text)
    for code in TIP :
        TIP_list.append(code.text)


    startnumber+=1000
    endnumber+=1000
    
Recipe_PRO['RECIPE_ID'] = RECIPE_ID_list
Recipe_PRO['COOKING_NO'] = COOKING_NO_list
Recipe_PRO['COOKING_DC'] = COOKING_DC_list
Recipe_PRO['stre_step_image_url'] = IMG_URL_list
Recipe_PRO['step_tip'] = TIP_list
    

recipe_description = pd.DataFrame(Recipe_PRO)
recipe_description.to_csv("recipe_description.csv")

# 모듈 import
import pandas as pd
from bs4 import BeautifulSoup
import requests

startnumber=1
endnumber=1000
Recipe_INFO = {}

RECIPE_ID_list = []
RECIPE_NM_KO_list = []
SUMRY_list = []
NATION_CODE_list = []
NATION_NM_list = []
TY_CODE_list = []
TY_NM_list = []
COOKING_TIME_list = []
CALORIE_list = []
QNT_list = []
LEVEL_NM_list = []
IRDNT_CODE_list = []
PC_NM_list = []
IMG_URL_list = []
DET_URL_list = []

while endnumber<=5000:
    #url 입력
    API_KEY = 'c41ba7a35737e92228906457385f7542b47a6f0549b1b90cfeabaf363c070e9e' #자기 키 입력하기
    url = 'http://211.237.50.150:7080/openapi/'+API_KEY+'/xml/Grid_20150827000000000226_1/'+str(startnumber)+'/'+str(endnumber)
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, 'html.parser')
    
    RECIPE_ID = soup.find_all('recipe_id')
    RECIPE_NM_KO = soup.find_all('recipe_nm_ko')
    SUMRY = soup.find_all('sumry')
    NATION_CODE = soup.find_all('nation_code')
    NATION_NM = soup.find_all('nation_nm')
    TY_CODE = soup.find_all('ty_code')
    TY_NM = soup.find_all('ty_nm')
    COOKING_TIME = soup.find_all('cooking_time')
    CALORIE = soup.find_all('calorie')
    QNT = soup.find_all('qnt')
    LEVEL_NM = soup.find_all('level_nm')
    IRDNT_CODE = soup.find_all('irdnt_code')
    PC_NM = soup.find_all('pc_nm')
    IMG_URL = soup.find_all('img_url')
    DET_URL = soup.find_all('det_url')
    
    for code in RECIPE_ID :
        RECIPE_ID_list.append(code.text)
    for code in RECIPE_NM_KO :
        RECIPE_NM_KO_list.append(code.text)
    for code in SUMRY :
        SUMRY_list.append(code.text)
    for code in NATION_CODE :
        NATION_CODE_list.append(code.text)
    for code in NATION_NM :
        NATION_NM_list.append(code.text)
    for code in TY_CODE :
        TY_CODE_list.append(code.text)
    for code in TY_NM :
        TY_NM_list.append(code.text)
    for code in COOKING_TIME :
        COOKING_TIME_list.append(code.text)
    for code in CALORIE :
        CALORIE_list.append(code.text)
    for code in QNT :
        QNT_list.append(code.text)
    for code in LEVEL_NM :
        LEVEL_NM_list.append(code.text)
    for code in IRDNT_CODE :
        IRDNT_CODE_list.append(code.text)
    for code in PC_NM :
        PC_NM_list.append(code.text)
    for code in IMG_URL :
        IMG_URL_list.append(code.text)
    for code in DET_URL :
        DET_URL_list.append(code.text)

    startnumber+=1000
    endnumber+=1000

    
Recipe_INFO['RECIPE_ID'] = RECIPE_ID_list
Recipe_INFO['RECIPE_NM_KO'] = RECIPE_NM_KO_list
Recipe_INFO['SUMRY'] = SUMRY_list
Recipe_INFO['NATION_CODE'] = NATION_CODE_list
Recipe_INFO['NATION_NM'] = NATION_NM_list
Recipe_INFO['TY_CODE'] = TY_CODE_list
Recipe_INFO['TY_NM'] = TY_NM_list
Recipe_INFO['COOKING_TIME'] = COOKING_TIME_list
Recipe_INFO['CALORIE'] = CALORIE_list
Recipe_INFO['QNT'] = QNT_list
Recipe_INFO['LEVEL_NM'] = LEVEL_NM_list
Recipe_INFO['IRDNT_CODE'] = IRDNT_CODE_list
Recipe_INFO['PC_NM'] = PC_NM_list
Recipe_INFO['IMG_URL'] = IMG_URL_list
Recipe_INFO['DET_URL'] = DET_URL_list
    

recipe_information = pd.DataFrame(Recipe_INFO)
recipe_information.to_csv("recipe_information.csv")

#!/usr/bin/env python
# coding: utf-8


# 모듈 import
import pandas as pd
from bs4 import BeautifulSoup
import requests

startnumber=1
endnumber=1000
Recipe_INGR = {}

RECIPE_ID_list=[]
IRDNT_SN_list=[]
IRDNT_NM_list=[]
IRDNT_CPCTY_list=[]
IRDNT_TY_CODE_list=[]
IRDNT_TY_NM_list=[]

while endnumber<=7000:
    #url 입력
    API_KEY = 'c41ba7a35737e92228906457385f7542b47a6f0549b1b90cfeabaf363c070e9e' #자기 키 입력하기
    url = 'http://211.237.50.150:7080/openapi/'+API_KEY+'/xml/Grid_20150827000000000227_1/'+str(startnumber)+'/'+str(endnumber)
    req = requests.get(url)
    html = req.text
    soup = BeautifulSoup(html, 'html.parser')
    
    RECIPE_ID = soup.find_all('recipe_id')
    IRDNT_SN = soup.find_all('irdnt_sn')
    IRDNT_NM = soup.find_all('irdnt_nm')
    IRDNT_CPCTY = soup.find_all('irdnt_cpcty')
    IRDNT_TY_CODE = soup.find_all('irdnt_ty_code')
    IRDNT_TY_NM = soup.find_all('irdnt_ty_nm')
    
    for code in RECIPE_ID :
        RECIPE_ID_list.append(code.text)
    for code in IRDNT_SN :
        IRDNT_SN_list.append(code.text)
    for code in IRDNT_NM :
        IRDNT_NM_list.append(code.text)
    for code in IRDNT_CPCTY :
        IRDNT_CPCTY_list.append(code.text)
    for code in IRDNT_TY_CODE :
        IRDNT_TY_CODE_list.append(code.text)
    for code in IRDNT_TY_NM :
        IRDNT_TY_NM_list.append(code.text)

    startnumber+=1000
    endnumber+=1000
    
Recipe_INGR['RECIPE_ID'] = RECIPE_ID_list
Recipe_INGR['IRDNT_SN'] = IRDNT_SN_list
Recipe_INGR['IRDNT_NM'] = IRDNT_NM_list
Recipe_INGR['IRDNT_CPCTY'] = IRDNT_CPCTY_list
Recipe_INGR['IRDNT_TY_CODE'] = IRDNT_TY_CODE_list
Recipe_INGR['IRDNT_TY_NM'] = IRDNT_TY_NM_list
    

recipe_ingredient = pd.DataFrame(Recipe_INGR)
recipe_ingredient.to_csv("recipe_ingredient.csv")